### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by Zaratusa** [comment]
You should be able to tranlate the item for your server using this guide: http://www.troubleinterroristtown.com/guides/translation
I think it's not useful to have all translation in the mod itself.

**Comment by Blueberryy** [comment]
bruh

**Comment by Blueberryy** [comment]
so you want to say that every user must translate his each ttt mod on server? would be better if mod will already support translation so he will don't need to translate 10000+ files

**Comment by Zaratusa** [comment]
I can't update all my mods every time anyone wants a new language. Sure it's easier for server owners, but the initial effort it takes to translate the mods to every language is huge. I can merge you pull request. But I won't update the mods for every language.

**Pull request merged**
